rmpflow_controller:
  ros__parameters:
    cspace_target_metric_scalar: 0.0
    cspace_target_position_gain: 25.0
    cspace_target_damping_gain: 18.0
    cspace_target_robust_position_term_thresh: 0.5
    cspace_target_inertia: 0.0
    joint_limit_metric_scalar: 0.0
    joint_limit_metric_length_scale: 0.01
    joint_limit_metric_exploder_eps: 0.001
    joint_limit_metric_velocity_gate_length_scale: 0.01
    joint_limit_accel_damper_gain: 200.0
    joint_limit_accel_potential_gain: 1.0
    joint_limit_accel_potential_exploder_eps: 0.01
    joint_limit_accel_potential_exploder_length_scale: 0.1
    joint_velocity_cap_max_velocity: 0.35
    joint_velocity_cap_velocity_damping_region: 0.05
    joint_velocity_cap_damping_gain: 18.0
    joint_velocity_cap_metric_weight: 0.0
    target_rmp_accel_p_gain: 100.0
    target_rmp_accel_d_gain: 15.0
    target_rmp_accel_norm_eps: 0.075
    target_rmp_metric_alpha_length_scale: 100000.0
    target_rmp_min_metric_alpha: 0.0
    target_rmp_max_metric_scalar: 50.0
    target_rmp_min_metric_scalar: 25.0
    target_rmp_proximity_metric_boost_scalar: 1.0
    target_rmp_proximity_metric_boost_length_scale: 1.0
    orientation_rmp_accel_p_gain: 6.0
    orientation_rmp_accel_d_gain: 8.0
    collision_rmp_metric_scalar: 0.0
    collision_rmp_margin: 0.0
    collision_rmp_damping_gain: 10.0
    collision_rmp_damping_std_dev: 0.12
    collision_rmp_damping_robustness_eps: 0.01
    collision_rmp_damping_velocity_gate_length_scale: 0.01
    collision_rmp_repulsion_gain: 16.0
    collision_rmp_repulsion_std_dev: 0.08
    collision_rmp_metric_modulation_radius: 0.22
    collision_rmp_metric_exploder_std_dev: 0.02
    collision_rmp_metric_exploder_eps: 0.001
    orientation_rmp_metric_scalar: 0.0
    damping_rmp_accel_d_gain: 80.0
    damping_rmp_metric_scalar: 0.0
    damping_rmp_inertia: 0.0
    graph:
      cspace_target:
        enabled: false
      tcp_orientation_x:
        enabled: false
      tcp_orientation_y:
        enabled: false
      tcp_orientation_z:
        enabled: false
