rmpflow_controller:
  ros__parameters:
    cspace_target_metric_scalar: 0.7
    cspace_target_inertia: 0.0
    joint_limit_metric_scalar: 0.0
    joint_velocity_cap_metric_weight: 0.0
    max_joint_accel: 25.0
    target_rmp_accel_p_gain: 140.0
    target_rmp_accel_d_gain: 55.0
    target_rmp_accel_norm_eps: 0.04
    target_rmp_metric_alpha_length_scale: 100000.0
    target_rmp_min_metric_alpha: 0.0
    target_rmp_max_metric_scalar: 180.0
    target_rmp_min_metric_scalar: 0.0
    target_rmp_proximity_metric_boost_scalar: 1.0
    target_rmp_proximity_metric_boost_length_scale: 1.0
    collision_rmp_metric_scalar: 0.0
    orientation_rmp_metric_scalar: 0.0
    damping_rmp_metric_scalar: 0.0
    damping_rmp_inertia: 0.0
